services:
  bot:
    build:
      context: ./bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongo

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    depends_on:
      - bot

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db
    command: ["--wiredTigerCacheSizeGB","0.25"]
