services:
  bot:
    build:
      context: ./bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./logs:/app/logs

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    depends_on:
      - bot
