services:
  bot:
    build:
      context: ./bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongo

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    depends_on:
      - bot

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db
    command: ["--wiredTigerCacheSizeGB","0.25"]
  yk:
    image: nosmoke-bot-bot
    command: ["node", "/app/yk-webhook-server.js"]
    environment:
      - YK_WEBHOOK_LOGIN=yk_user
      - YK_WEBHOOK_PASSWORD=super-secret
    depends_on:
      - mongo
    restart: unless-stopped

  payments:
    image: nosmoke-bot-bot
    command: ["node", "/app/payments-notifier.js"]
    env_file: .env
    environment:
      - QUIET_OVERRIDE_PAYMENTS=0
      - ALERT_PAYMENTS=1
      - ADMIN_TG_ID=363098548
    depends_on:
      - mongo
    restart: unless-stopped
