name: Deploy to VPS

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-main
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_vps
          chmod 600 ~/.ssh/id_vps
          ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

      - name: Rsync to VPS
        run: |
          rsync -az --delete \
            --exclude '.git' \
            --exclude 'node_modules/' \
            --exclude 'logs/' \
            --exclude 'caddy/data/' \
            --exclude 'caddy/config/' \
            --exclude '.env' \
            -e "ssh -i ~/.ssh/id_vps -o StrictHostKeyChecking=yes" \
            ./ "${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_PATH }}/"

      - name: Compose up
        run: |
          ssh -i ~/.ssh/id_vps -o StrictHostKeyChecking=yes \
            "${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}" \
            "cd '${{ secrets.VPS_PATH }}' && docker compose up -d --build"
